[project]
name = "advertisement"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Azamat", email = "azamat_azamatov@epam.com"},
]
dependencies = ["uvicorn", "fastapi", "pymongo"]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
